version: 2

updates:

  - package-ecosystem: gomod
    directories:
      - /
      - /tools/protoc-gen-go-netconn
      - /tools/go-generate-qemu-devices
    target-branch: staging
    schedule:
      interval: weekly
      day: sunday
      time: '09:00'
    commit-message:
      prefix: gomod # Prefix messages with
      include: scope # List all updated dependencies
    groups:
      go-deps:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '09:00'
