#! .goreleaser.yaml
changelog:
  use: github

release:
  github:
    owner: unikraft
    name: kraftkit
  draft: false
  prerelease: true
  mode: replace
  header: |
    ## KraftKit {{ .Tag }} ({{ .Date }})

    This is the pre-release version of KraftKit.
  name_template: 'v{{ .Version }}'

nfpms:
  - vendor: Unikraft
    maintainer: Alexander Jung <alex@unikraft.io>
    description: Build and use highly customized and ultra-lightweight unikernels.
    license: BSD 3-clause
    bindir: /usr/local/bin
    homepage: https://kraftkit.sh
    dependencies:
      - libc6 (>= 2.14)
    formats:
      - deb
      - rpm
      - apk

builds:
#@ for binary in ["kraft"]:
  - id: #@ "{}-linuxu".format(binary)
    binary: #@ binary
    main: #@ "./cmd/{}".format(binary)
    env:
      - CGO_ENABLED=1
      - GOMOD=kraftkit.sh
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w 
      - -X {{ .Env.GOMOD }}/internal/version.version={{ .Version }}
      - -X {{ .Env.GOMOD }}/internal/version.commit={{ .Commit }}
      - -X {{ .Env.GOMOD }}/internal/version.buildTime={{ .Date }}
    tags:
      - static
    hooks:
      pre: make git2go
#@ end
