#! .goreleaser.yaml
#@ binaries = {
#@   "kraft": {
#@     "darwin": ["amd64", "arm64"],
#@     "freebsd": ["amd64", "arm64"],
#@     "linux": ["amd64", "arm64"],
#@   },
#@   "runu": {
#@     "linux": ["amd64"],
#@   },
#@ }
changelog:
  sort: asc
  use: github
  filters:
    include:
      - '^.*#[[:digit:]]+.*$'
  groups:
    - title: ⚠️ Breaking Changes
      regexp: '^[[:xdigit:]]+: [[:lower:]]+(\(.*\))?!:.*$'
      order: 1
    - title: 🚀 New Features
      regexp: '^[[:xdigit:]]+: feat(\(.*\))?:.*$'
      order: 2
    - title: 🐛 Bug Fixes
      regexp: '^[[:xdigit:]]+: fix(\(.*\))?:.*$'
      order: 3
    - title: 📖 Docs
      regexp: '^[[:xdigit:]]+: docs(\(.*\))?:.*$'
      order: 4
    - title: 🤖 Bumps
      regexp: '^[[:xdigit:]]+: (gomod|build)\(deps\):.*$'
      order: 5
    - title: 🐒 Miscellaneous
      order: 999

release:
  github:
    owner: unikraft
    name: kraftkit
  draft: false
  prerelease: false
  mode: replace
  header: |
    ## KraftKit {{ .Tag }} ({{ .Date }})

    Release of kraftkit.
  name_template: 'v{{ .Version }}'

signs:
  - id: cosign
    cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    args:
      - sign-blob
      - "--key=cosign.key"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all

nfpms:
  - vendor: Unikraft
    id: nfpm-default
    maintainer: Alexander Jung <alex@unikraft.io>
    description: Build and use highly customized and ultra-lightweight unikernels.
    license: BSD 3-clause
    bindir: /usr/local/bin
    homepage: https://kraftkit.sh
    formats:
      - deb
      - rpm
      - apk
    recommends:
      - bison
      - build-essential
      - flex
      - git
      - libncurses-dev
      - qemu-system
      - socat
      - unzip
      - wget
    suggests:
      - gcc-x86-64-linux-gnu
      - g++-x86-64-linux-gnu
    contents:
      - src: scripts/kraftld
        dst: /usr/local/bin/kraftld

aurs:
  - homepage: https://kraftkit.sh
    ids:
#@ for arch in binaries["kraft"]["linux"]:
      - #@ "archive-kraft-linux-{}".format(arch)
#@ end
    description: Build and use highly customized and ultra-lightweight unikernels
    maintainers:
      - "Alexander Jung <alex at unikraft dot io>"
    license: "BSD-3-Clause"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/kraftkit-bin.git"
    package: |-
      # kraft
      install -Dm755 "${srcdir}/kraft" "${pkgdir}/usr/bin/kraft"
      # kraftld
      install -Dm755 "${srcdir}/kraftld" "${pkgdir}/usr/bin/kraftld"
    commit_author:
      name: Unikraft Bot
      email: monkey+aur@unikraft.io

nix:
  - name: kraftkit
    ids:
#@ for arch in binaries["kraft"]["linux"]:
      - #@ "archive-kraft-linux-{}".format(arch)
#@ end
    repository:
      owner: unikraft
      name: nur
    homepage: https://kraftkit.sh
    description: Build and use highly customized and ultra-lightweight unikernels
    path: pkgs/kraftkit/default.nix
    license: bsd3
    install: |-
      mkdir -p $out/bin
      cp -vr ./dist/kraft $out/bin/kraft
      cp -vr ./dist/kraftld $out/bin/kraftld

brews:
  - name: kraftkit
    ids:
#@ for arch in binaries["kraft"]["linux"]:
      - #@ "archive-kraft-linux-{}".format(arch)
#@ end
#@ for arch in binaries["kraft"]["darwin"]:
      - #@ "archive-kraft-darwin-{}".format(arch)
#@ end
    url_template: "https://github.com/unikraft/kraftkit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Unikraft Bot
      email: monkey@unikraft.io
    commit_msg_template: "Bump {{ .ProjectName }} to version {{ .Tag }}"
    homepage: "https://kraftkit.sh"
    description: "Build and use highly customized and ultra-lightweight unikernels."
    license: "BSD-3-Clause"
    skip_upload: false
    dependencies:
      - name: gnu-sed
      - name: make
      - name: coreutils
      - name: m4
      - name: gawk
      - name: grep
      - name: wget
      - name: qemu
      - name: socat
      - name: x86_64-elf-binutils
      - name: x86_64-elf-gcc
      - name: aarch64-elf-binutils
      - name: aarch64-elf-gcc
    repository:
      owner: unikraft
      name: homebrew-cli

builds:
#@ for bin, oses in binaries.items():
#@ for os, archs in oses.items():
#@ for arch in archs:
  - id: #@ "{}-{}-{}".format(bin, os, arch)
    binary: #@ bin
    main: #@ "./cmd/{}".format(bin)
    env:
    #@ if bin == "runu":
      - CGO_ENABLED=1
    #@ else:
      - CGO_ENABLED=0
    #@ end
      - GOMOD=kraftkit.sh
    goos:
      - #@ os
    goarch:
      - #@ arch
    ldflags:
      - -s -w
      - -X {{ .Env.GOMOD }}/internal/version.version={{ .Version }}
      - -X {{ .Env.GOMOD }}/internal/version.commit={{ .Commit }}
      - -X {{ .Env.GOMOD }}/internal/version.buildTime={{ .Date }}
    tags:
      - containers_image_storage_stub
      - containers_image_openpgp
#@ end
#@ end
#@ end

archives:
#@ for os, archs in binaries["kraft"].items():
#@ for arch in archs:
  - id: #@ "archive-kraft-{}-{}".format(os, arch)
    format: tar.gz
    name_template: kraft_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    builds:
      - #@ "kraft-{}-{}".format(os, arch)
    files:
      - src: scripts/kraftld
        strip_parent: true
        info:
          mode: 0755
#@ end
#@ end

#@ for os, archs in binaries["runu"].items():
#@ for arch in archs:
  - id: #@ "archive-runu-{}-{}".format(os, arch)
    format: tar.gz
    name_template: runu_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    builds:
      - #@ "runu-{}-{}".format(os, arch)
#@ end
#@ end
