// Code generated by kraftkit.sh/tools/protoc-gen-go-netconn. DO NOT EDIT.
// source: machine/qemu/qmp/v7alpha2/control.proto

package qmpv7alpha2

type Capability string

const (
	oob = Capability("oob")
)

func (e Capability) String() string {
	return string(e)
}

func Capabilitys() []Capability {
	return []Capability{
		oob,
	}
}

type CapabilitiesRequest struct {
	Execute string `json:"execute" default:"qmp_capabilities"`

	Arguments CapabilitiesRequestArguments `json:"arguments,omitempty"`
}

type CapabilitiesRequestArguments struct {
	Enable []Capability `json:"enable"`
}

type QuitRequest struct {
	Execute string `json:"execute" default:"quit"`
}

type QuitResponse struct {
}
