// Code generated by kraftkit.sh/tools/protoc-gen-go-netconn. DO NOT EDIT.
// source: machine/qemu/qmp/v7alpha2/error.proto

package qmpv7alpha2

type ErrorResponse struct {
	Class       string `json:"class"`
	Cescription string `json:"desc"`
}
