// Code generated by kraftkit.sh/tools/protoc-gen-go-netconn. DO NOT EDIT.
// source: machine/qemu/qmp/v7alpha2/greeting.proto

package qmpv7alpha2

type GreetingVersionTriple struct {
	Major uint32 `json:"major"`
	Minor uint32 `json:"minor"`
	Micro uint32 `json:"micro"`
}

type GreetingVersion struct {
	Qemu    GreetingVersionTriple `json:"qemu"`
	Package string                `json:"package"`
}

type Greeting struct {
	Version      GreetingVersion `json:"version"`
	Capabilities []Capability    `json:"capabilities"`
}

type GreetingResponse struct {
	Qmp Greeting `json:"QMP"`
}

type GreetingRequest struct {
}
