// Code generated by kraftkit.sh/tools/protoc-gen-go-netconn. DO NOT EDIT.
// source: machine/qemu/qmp/v7alpha2/machine.proto

package qmpv7alpha2

type QueryKvmRequest struct {
	Execute string `json:"execute" default:"query-kvm"`
}

type KvmInfo struct {
	Enabled bool `json:"enabled"`
	Present bool `json:"present"`
}

type QueryKvmResponse struct {
	Return KvmInfo `json:"return"`
}

type SystemResetRequest struct {
	Execute string `json:"execute" default:"system_reset"`
}

type SystemPowerdownRequest struct {
	Execute string `json:"execute" default:"system_powerdown"`
}

type SystemWakeupRequest struct {
	Execute string `json:"execute" default:"system_Wakeup"`
}
