// Code generated by kraftkit.sh/tools/protoc-gen-go-netconn. DO NOT EDIT.
// source: machine/qemu/qmp/v1alpha/error.proto

package qmpv1alpha

type ErrorResponse struct {
	Class       string `json:"class"`
	Cescription string `json:"desc"`
}
