// Code generated by kraftkit.sh/tools/protoc-gen-go-netconn. DO NOT EDIT.
// source: machine/qemu/qmp/v1alpha/misc.proto

package qmpv1alpha

type StopRequest struct {
	Execute string `json:"execute" default:"stop"`
}

type StopResponse struct {
}

type ContRequest struct {
	Execute string `json:"execute" default:"cont"`
}

type ContResponse struct {
}
