#!/bin/sh
set -e

# cleanup-artifacts
#
# Removes runtime/cache data generated by kraftkit.
#
# Design goals:
#  - Idempotent (safe to run multiple times)
#  - Works without optional dependencies (yq)
#  - Never deletes unintended paths
#  - Never fails package uninstall

CONFIG="${HOME}/.config/kraftkit/config.yaml"

# Default runtime directories created by KraftKit.
CACHE_DIR="${HOME}/.cache/kraftkit"
DATA_DIR="${HOME}/.local/share/kraftkit"


# If a config exists and yq is available, read custom paths.
# Fallback to defaults to ensure cleanup always succeeds.
if [ -f "$CONFIG" ] && command -v yq >/dev/null 2>&1; then
  CACHE_DIR="$(yq '.paths.cache // "'"$CACHE_DIR"'"' "$CONFIG")"
  DATA_DIR="$(yq '.paths.data // "'"$DATA_DIR"'"' "$CONFIG")"
fi


# Safety guards:
#  - non empty
#  - not root directory
#  - ignore missing paths
[ -n "$CACHE_DIR" ] && [ "$CACHE_DIR" != "/" ] && rm -rf -- "$CACHE_DIR" || true
[ -n "$DATA_DIR" ] && [ "$DATA_DIR" != "/" ] && rm -rf -- "$DATA_DIR" || true
