// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2022, Unikraft GmbH and The KraftKit Authors.
// Licensed under the BSD-3-Clause License (the "License").
// You may not use this file except in compliance with the License.
package qemu

import (
	"fmt"
	"strings"
)

type (
	QemuCPUFeature  string
	QemuCPUFeatures []QemuCPUFeature
)

type QemuCPU struct {
	CPU fmt.Stringer     `json:"arch"`
	On  []QemuCPUFeature `json:"on"`
	Off []QemuCPUFeature `json:"off"`
}

func (cpu QemuCPU) String() string {
	if cpu.CPU == nil {
		return ""
	}

	var ret strings.Builder

	ret.WriteString(cpu.CPU.String())

	if len(cpu.On) > 0 {
		for _, on := range cpu.On {
			ret.WriteString(",+")
			ret.WriteString(string(on))
		}
	}

	if len(cpu.Off) > 0 {
		for _, off := range cpu.Off {
			ret.WriteString(",-")
			ret.WriteString(string(off))
		}
	}

	return ret.String()
}

type QemuCPUX86 string

func (x86 QemuCPUX86) String() string {
	return string(x86)
}

type QemuCPUArm string

func (arm QemuCPUArm) String() string {
	return string(arm)
}

const (
	QemuCPUX86486                    = QemuCPUX86("486")
	QemuCPUX86486V1                  = QemuCPUX86("486-v1")
	QemuCPUX86Broadwell              = QemuCPUX86("Broadwell")
	QemuCPUX86BroadwellIBRS          = QemuCPUX86("Broadwell-IBRS")
	QemuCPUX86BroadwellNoTSX         = QemuCPUX86("Broadwell-noTSX")
	QemuCPUX86BroadwellNoTSXIBRS     = QemuCPUX86("Broadwell-noTSX-IBRS")
	QemuCPUX86BroadwellV1            = QemuCPUX86("Broadwell-v1")
	QemuCPUX86BroadwellV2            = QemuCPUX86("Broadwell-v2")
	QemuCPUX86BroadwellV3            = QemuCPUX86("Broadwell-v3")
	QemuCPUX86BroadwellV4            = QemuCPUX86("Broadwell-v4")
	QemuCPUX86CascadelakeServer      = QemuCPUX86("Cascadelake-Server")
	QemuCPUX86CascadelakeServerNoTSX = QemuCPUX86("Cascadelake-Server-noTSX")
	QemuCPUX86CascadelakeServerV1    = QemuCPUX86("Cascadelake-Server-v1")
	QemuCPUX86CascadelakeServerV2    = QemuCPUX86("Cascadelake-Server-v2")
	QemuCPUX86CascadelakeServerV3    = QemuCPUX86("Cascadelake-Server-v3")
	QemuCPUX86CascadelakeServerV4    = QemuCPUX86("Cascadelake-Server-v4")
	QemuCPUX86Conroe                 = QemuCPUX86("Conroe")
	QemuCPUX86ConroeV1               = QemuCPUX86("Conroe-v1")
	QemuCPUX86Cooperlake             = QemuCPUX86("Cooperlake")
	QemuCPUX86CooperlakeV1           = QemuCPUX86("Cooperlake-v1")
	QemuCPUX86Denverton              = QemuCPUX86("Denverton")
	QemuCPUX86DenvertonV1            = QemuCPUX86("Denverton-v1")
	QemuCPUX86DenvertonV2            = QemuCPUX86("Denverton-v2")
	QemuCPUX86Dhyana                 = QemuCPUX86("Dhyana")
	QemuCPUX86DhyanaV1               = QemuCPUX86("Dhyana-v1")
	QemuCPUX86EPYC                   = QemuCPUX86("EPYC")
	QemuCPUX86EPYCIBPB               = QemuCPUX86("EPYC-IBPB")
	QemuCPUX86EPYCRome               = QemuCPUX86("EPYC-Rome")
	QemuCPUX86EPYCRomeV1             = QemuCPUX86("EPYC-Rome-v1")
	QemuCPUX86EPYCV1                 = QemuCPUX86("EPYC-v1")
	QemuCPUX86EPYCV2                 = QemuCPUX86("EPYC-v2")
	QemuCPUX86EPYCV3                 = QemuCPUX86("EPYC-v3")
	QemuCPUX86Haswell                = QemuCPUX86("Haswell")
	QemuCPUX86HaswellIBRS            = QemuCPUX86("Haswell-IBRS")
	QemuCPUX86HaswellNoTSX           = QemuCPUX86("Haswell-noTSX")
	QemuCPUX86HaswellNoTSXIBRS       = QemuCPUX86("Haswell-noTSX-IBRS")
	QemuCPUX86HaswellV1              = QemuCPUX86("Haswell-v1")
	QemuCPUX86HaswellV2              = QemuCPUX86("Haswell-v2")
	QemuCPUX86HaswellV3              = QemuCPUX86("Haswell-v3")
	QemuCPUX86HaswellV4              = QemuCPUX86("Haswell-v4")
	QemuCPUX86IcelakeClient          = QemuCPUX86("Icelake-Client")
	QemuCPUX86IcelakeClientNoTSX     = QemuCPUX86("Icelake-Client-noTSX")
	QemuCPUX86IcelakeClientV1        = QemuCPUX86("Icelake-Client-v1")
	QemuCPUX86IcelakeClientV2        = QemuCPUX86("Icelake-Client-v2")
	QemuCPUX86IcelakeServer          = QemuCPUX86("Icelake-Server")
	QemuCPUX86IcelakeServerNoTSX     = QemuCPUX86("Icelake-Server-noTSX")
	QemuCPUX86IcelakeServerV1        = QemuCPUX86("Icelake-Server-v1")
	QemuCPUX86IcelakeServerV2        = QemuCPUX86("Icelake-Server-v2")
	QemuCPUX86IcelakeServerV3        = QemuCPUX86("Icelake-Server-v3")
	QemuCPUX86IcelakeServerV4        = QemuCPUX86("Icelake-Server-v4")
	QemuCPUX86IvyBridge              = QemuCPUX86("IvyBridge")
	QemuCPUX86IvyBridgeIBRS          = QemuCPUX86("IvyBridge-IBRS")
	QemuCPUX86IvyBridgeV1            = QemuCPUX86("IvyBridge-v1")
	QemuCPUX86IvyBridgeV2            = QemuCPUX86("IvyBridge-v2")
	QemuCPUX86KnightsMill            = QemuCPUX86("KnightsMill")
	QemuCPUX86KnightsMillV1          = QemuCPUX86("KnightsMill-v1")
	QemuCPUX86Nehalem                = QemuCPUX86("Nehalem")
	QemuCPUX86NehalemIBRS            = QemuCPUX86("Nehalem-IBRS")
	QemuCPUX86NehalemV1              = QemuCPUX86("Nehalem-v1")
	QemuCPUX86NehalemV2              = QemuCPUX86("Nehalem-v2")
	QemuCPUX86Opteron_G1             = QemuCPUX86("Opteron_G1")
	QemuCPUX86Opteron_G1V1           = QemuCPUX86("Opteron_G1-v1")
	QemuCPUX86Opteron_G2             = QemuCPUX86("Opteron_G2")
	QemuCPUX86Opteron_G2V1           = QemuCPUX86("Opteron_G2-v1")
	QemuCPUX86Opteron_G3             = QemuCPUX86("Opteron_G3")
	QemuCPUX86Opteron_G3V1           = QemuCPUX86("Opteron_G3-v1")
	QemuCPUX86Opteron_G4             = QemuCPUX86("Opteron_G4")
	QemuCPUX86Opteron_G4V1           = QemuCPUX86("Opteron_G4-v1")
	QemuCPUX86Opteron_G5             = QemuCPUX86("Opteron_G5")
	QemuCPUX86Opteron_G5V1           = QemuCPUX86("Opteron_G5-v1")
	QemuCPUX86Penryn                 = QemuCPUX86("Penryn")
	QemuCPUX86PenrynV1               = QemuCPUX86("Penryn-v1")
	QemuCPUX86SandyBridge            = QemuCPUX86("SandyBridge")
	QemuCPUX86SandyBridgeIBRS        = QemuCPUX86("SandyBridge-IBRS")
	QemuCPUX86SandyBridgeV1          = QemuCPUX86("SandyBridge-v1")
	QemuCPUX86SandyBridgeV2          = QemuCPUX86("SandyBridge-v2")
	QemuCPUX86SkylakeClient          = QemuCPUX86("Skylake-Client")
	QemuCPUX86SkylakeClientIBRS      = QemuCPUX86("Skylake-Client-IBRS")
	QemuCPUX86SkylakeClientNoTSXIBR  = QemuCPUX86("Skylake-Client-noTSX-IBR")
	QemuCPUX86SkylakeClientV1        = QemuCPUX86("Skylake-Client-v1")
	QemuCPUX86SkylakeClientV2        = QemuCPUX86("Skylake-Client-v2")
	QemuCPUX86SkylakeClientV3        = QemuCPUX86("Skylake-Client-v3")
	QemuCPUX86SkylakeServer          = QemuCPUX86("Skylake-Server")
	QemuCPUX86SkylakeServerIBRS      = QemuCPUX86("Skylake-Server-IBRS")
	QemuCPUX86SkylakeServerNoTSXIBRS = QemuCPUX86("Skylake-Server-noTSX-IBRS")
	QemuCPUX86SkylakeServerV1        = QemuCPUX86("Skylake-Server-v1")
	QemuCPUX86SkylakeServerV2        = QemuCPUX86("Skylake-Server-v2")
	QemuCPUX86SkylakeServerV3        = QemuCPUX86("Skylake-Server-v3")
	QemuCPUX86SkylakeServerV4        = QemuCPUX86("Skylake-Server-v4")
	QemuCPUX86Snowridge              = QemuCPUX86("Snowridge")
	QemuCPUX86SnowridgeV1            = QemuCPUX86("Snowridge-v1")
	QemuCPUX86SnowridgeV2            = QemuCPUX86("Snowridge-v2")
	QemuCPUX86Westmere               = QemuCPUX86("Westmere")
	QemuCPUX86WestmereIBRS           = QemuCPUX86("Westmere-IBRS")
	QemuCPUX86WestmereV1             = QemuCPUX86("Westmere-v1")
	QemuCPUX86WestmereV2             = QemuCPUX86("Westmere-v2")
	QemuCPUX86Athlon                 = QemuCPUX86("athlon")
	QemuCPUX86AthlonV1               = QemuCPUX86("athlon-v1")
	QemuCPUX86Core2duo               = QemuCPUX86("core2duo")
	QemuCPUX86Core2duoV1             = QemuCPUX86("core2duo-v1")
	QemuCPUX86Coreduo                = QemuCPUX86("coreduo")
	QemuCPUX86CoreduoV1              = QemuCPUX86("coreduo-v1")
	QemuCPUX86Kvm32                  = QemuCPUX86("kvm32")
	QemuCPUX86Kvm32V1                = QemuCPUX86("kvm32-v1")
	QemuCPUX86Kvm64                  = QemuCPUX86("kvm64")
	QemuCPUX86Kvm64V1                = QemuCPUX86("kvm64-v1")
	QemuCPUX86N270                   = QemuCPUX86("n270")
	QemuCPUX86N270V1                 = QemuCPUX86("n270-v1")
	QemuCPUX86Pentium                = QemuCPUX86("pentium")
	QemuCPUX86PentiumV1              = QemuCPUX86("pentium-v1")
	QemuCPUX86Pentium2               = QemuCPUX86("pentium2")
	QemuCPUX86Pentium2V1             = QemuCPUX86("pentium2-v1")
	QemuCPUX86Pentium3               = QemuCPUX86("pentium3")
	QemuCPUX86Pentium3V1             = QemuCPUX86("pentium3-v1")
	QemuCPUX86Phenom                 = QemuCPUX86("phenom")
	QemuCPUX86PhenomV1               = QemuCPUX86("phenom-v1")
	QemuCPUX86Qemu32                 = QemuCPUX86("qemu32")
	QemuCPUX86Qemu32V1               = QemuCPUX86("qemu32-v1")
	QemuCPUX86Qemu64                 = QemuCPUX86("qemu64")
	QemuCPUX86Qemu64V1               = QemuCPUX86("qemu64-v1")
	QemuCPUX86Base                   = QemuCPUX86("base")
	QemuCPUX86Host                   = QemuCPUX86("host")
	QemuCPUX86Max                    = QemuCPUX86("max")
)

const (
	QemuCPUArm1026      = QemuCPUArm("arm1026")
	QemuCPUArm1136      = QemuCPUArm("arm1136")
	QemuCPUArm1136R2    = QemuCPUArm("arm1136-r2")
	QemuCPUArm1176      = QemuCPUArm("arm1176")
	QemuCPUArm11mpcore  = QemuCPUArm("arm11mpcore")
	QemuCPUArm926       = QemuCPUArm("arm926")
	QemuCPUArm946       = QemuCPUArm("arm946")
	QemuCPUArmCortexA15 = QemuCPUArm("cortex-a15")
	QemuCPUArmCortexA53 = QemuCPUArm("cortex-a53")
	QemuCPUArmCortexA7  = QemuCPUArm("cortex-a7")
	QemuCPUArmCortexA8  = QemuCPUArm("cortex-a8")
	QemuCPUArmCortexA9  = QemuCPUArm("cortex-a9")
	QemuCPUArmCortexM0  = QemuCPUArm("cortex-m0")
	QemuCPUArmCortexM3  = QemuCPUArm("cortex-m3")
	QemuCPUArmCortexM33 = QemuCPUArm("cortex-m33")
	QemuCPUArmCortexM4  = QemuCPUArm("cortex-m4")
	QemuCPUArmCortexM7  = QemuCPUArm("cortex-m7")
	QemuCPUArmCortexR5  = QemuCPUArm("cortex-r5")
	QemuCPUArmCortexR5f = QemuCPUArm("cortex-r5f")
	QemuCPUArmMax       = QemuCPUArm("max")
	QemuCPUArmPxa250    = QemuCPUArm("pxa250")
	QemuCPUArmPxa255    = QemuCPUArm("pxa255")
	QemuCPUArmPxa260    = QemuCPUArm("pxa260")
	QemuCPUArmPxa261    = QemuCPUArm("pxa261")
	QemuCPUArmPxa262    = QemuCPUArm("pxa262")
	QemuCPUArmPxa270A0  = QemuCPUArm("pxa270-a0")
	QemuCPUArmPxa270A1  = QemuCPUArm("pxa270-a1")
	QemuCPUArmPxa270    = QemuCPUArm("pxa270")
	QemuCPUArmPxa270B0  = QemuCPUArm("pxa270-b0")
	QemuCPUArmPxa270B1  = QemuCPUArm("pxa270-b1")
	QemuCPUArmPxa270C0  = QemuCPUArm("pxa270-c0")
	QemuCPUArmPxa270C5  = QemuCPUArm("pxa270-c5")
	QemuCPUArmSa1100    = QemuCPUArm("sa1100")
	QemuCPUArmSa1110    = QemuCPUArm("sa1110")
	QemuCPUArmTi925t    = QemuCPUArm("ti925t")
)

const (
	QemuCPUFeature3dnow                           = QemuCPUFeature("3dnow")
	QemuCPUFeature3dnowext                        = QemuCPUFeature("3dnowext")
	QemuCPUFeature3dnowprefetch                   = QemuCPUFeature("3dnowprefetch")
	QemuCPUFeatureAbm                             = QemuCPUFeature("abm")
	QemuCPUFeatureAce2                            = QemuCPUFeature("ace2")
	QemuCPUFeatureAce2En                          = QemuCPUFeature("ace2-en")
	QemuCPUFeatureAcpi                            = QemuCPUFeature("acpi")
	QemuCPUFeatureAdx                             = QemuCPUFeature("adx")
	QemuCPUFeatureAes                             = QemuCPUFeature("aes")
	QemuCPUFeatureAmdNoSsb                        = QemuCPUFeature("amd-no-ssb")
	QemuCPUFeatureAmdSsbd                         = QemuCPUFeature("amd-ssbd")
	QemuCPUFeatureAmdStibp                        = QemuCPUFeature("amd-stibp")
	QemuCPUFeatureApic                            = QemuCPUFeature("apic")
	QemuCPUFeatureArat                            = QemuCPUFeature("arat")
	QemuCPUFeatureArchCapabilities                = QemuCPUFeature("arch-capabilities")
	QemuCPUFeatureAvx                             = QemuCPUFeature("avx")
	QemuCPUFeatureAvx2                            = QemuCPUFeature("avx2")
	QemuCPUFeatureAvx5124fmaps                    = QemuCPUFeature("avx512-4fmaps")
	QemuCPUFeatureAvx5124vnniw                    = QemuCPUFeature("avx512-4vnniw")
	QemuCPUFeatureAvx512Bf16                      = QemuCPUFeature("avx512-bf16")
	QemuCPUFeatureAvx512bitalg                    = QemuCPUFeature("avx512bitalg")
	QemuCPUFeatureAvx512bw                        = QemuCPUFeature("avx512bw")
	QemuCPUFeatureAvx512cd                        = QemuCPUFeature("avx512cd")
	QemuCPUFeatureAvx512dq                        = QemuCPUFeature("avx512dq")
	QemuCPUFeatureAvx512er                        = QemuCPUFeature("avx512er")
	QemuCPUFeatureAvx512f                         = QemuCPUFeature("avx512f")
	QemuCPUFeatureAvx512ifma                      = QemuCPUFeature("avx512ifma")
	QemuCPUFeatureAvx512pf                        = QemuCPUFeature("avx512pf")
	QemuCPUFeatureAvx512vbmi                      = QemuCPUFeature("avx512vbmi")
	QemuCPUFeatureAvx512vbmi2                     = QemuCPUFeature("avx512vbmi2")
	QemuCPUFeatureAvx512vl                        = QemuCPUFeature("avx512vl")
	QemuCPUFeatureAvx512vnni                      = QemuCPUFeature("avx512vnni")
	QemuCPUFeatureAvx512Vp2intersect              = QemuCPUFeature("avx512-vp2intersect")
	QemuCPUFeatureAvx512Vpopcntdq                 = QemuCPUFeature("avx512-vpopcntdq")
	QemuCPUFeatureBmi1                            = QemuCPUFeature("bmi1")
	QemuCPUFeatureBmi2                            = QemuCPUFeature("bmi2")
	QemuCPUFeatureCid                             = QemuCPUFeature("cid")
	QemuCPUFeatureCldemote                        = QemuCPUFeature("cldemote")
	QemuCPUFeatureClflush                         = QemuCPUFeature("clflush")
	QemuCPUFeatureClflushopt                      = QemuCPUFeature("clflushopt")
	QemuCPUFeatureClwb                            = QemuCPUFeature("clwb")
	QemuCPUFeatureClzero                          = QemuCPUFeature("clzero")
	QemuCPUFeatureCmov                            = QemuCPUFeature("cmov")
	QemuCPUFeatureCmpLegacy                       = QemuCPUFeature("cmp-legacy")
	QemuCPUFeatureCoreCapability                  = QemuCPUFeature("core-capability")
	QemuCPUFeatureCr8legacy                       = QemuCPUFeature("cr8legacy")
	QemuCPUFeatureCx16                            = QemuCPUFeature("cx16")
	QemuCPUFeatureCx8                             = QemuCPUFeature("cx8")
	QemuCPUFeatureDca                             = QemuCPUFeature("dca")
	QemuCPUFeatureDe                              = QemuCPUFeature("de")
	QemuCPUFeatureDecodeassists                   = QemuCPUFeature("decodeassists")
	QemuCPUFeatureDs                              = QemuCPUFeature("ds")
	QemuCPUFeatureDsCpl                           = QemuCPUFeature("ds-cpl")
	QemuCPUFeatureDtes64                          = QemuCPUFeature("dtes64")
	QemuCPUFeatureErms                            = QemuCPUFeature("erms")
	QemuCPUFeatureEst                             = QemuCPUFeature("est")
	QemuCPUFeatureExtapic                         = QemuCPUFeature("extapic")
	QemuCPUFeatureF16c                            = QemuCPUFeature("f16c")
	QemuCPUFeatureFlushbyasid                     = QemuCPUFeature("flushbyasid")
	QemuCPUFeatureFma                             = QemuCPUFeature("fma")
	QemuCPUFeatureFma4                            = QemuCPUFeature("fma4")
	QemuCPUFeatureFpu                             = QemuCPUFeature("fpu")
	QemuCPUFeatureFsgsbase                        = QemuCPUFeature("fsgsbase")
	QemuCPUFeatureFsrm                            = QemuCPUFeature("fsrm")
	QemuCPUFeatureFullWidthWrite                  = QemuCPUFeature("full-width-write")
	QemuCPUFeatureFxsr                            = QemuCPUFeature("fxsr")
	QemuCPUFeatureFxsrOpt                         = QemuCPUFeature("fxsr-opt")
	QemuCPUFeatureGfni                            = QemuCPUFeature("gfni")
	QemuCPUFeatureHle                             = QemuCPUFeature("hle")
	QemuCPUFeatureHt                              = QemuCPUFeature("ht")
	QemuCPUFeatureHypervisor                      = QemuCPUFeature("hypervisor")
	QemuCPUFeatureIa64                            = QemuCPUFeature("ia64")
	QemuCPUFeatureIbpb                            = QemuCPUFeature("ibpb")
	QemuCPUFeatureIbrsAll                         = QemuCPUFeature("ibrs-all")
	QemuCPUFeatureIbs                             = QemuCPUFeature("ibs")
	QemuCPUFeatureIntelPt                         = QemuCPUFeature("intel-pt")
	QemuCPUFeatureInvpcid                         = QemuCPUFeature("invpcid")
	QemuCPUFeatureInvtsc                          = QemuCPUFeature("invtsc")
	QemuCPUFeatureKvmAsyncpf                      = QemuCPUFeature("kvm-asyncpf")
	QemuCPUFeatureKvmAsyncpfInt                   = QemuCPUFeature("kvm-asyncpf-int")
	QemuCPUFeatureKvmclock                        = QemuCPUFeature("kvmclock")
	QemuCPUFeatureKvmclockStableBit               = QemuCPUFeature("kvmclock-stable-bit")
	QemuCPUFeatureKvmHintDedicated                = QemuCPUFeature("kvm-hint-dedicated")
	QemuCPUFeatureKvmMmu                          = QemuCPUFeature("kvm-mmu")
	QemuCPUFeatureKvmNopiodelay                   = QemuCPUFeature("kvm-nopiodelay")
	QemuCPUFeatureKvmPollControl                  = QemuCPUFeature("kvm-poll-control")
	QemuCPUFeatureKvmPvEoi                        = QemuCPUFeature("kvm-pv-eoi")
	QemuCPUFeatureKvmPvIpi                        = QemuCPUFeature("kvm-pv-ipi")
	QemuCPUFeatureKvmPvSchedYield                 = QemuCPUFeature("kvm-pv-sched-yield")
	QemuCPUFeatureKvmPvTlbFlush                   = QemuCPUFeature("kvm-pv-tlb-flush")
	QemuCPUFeatureKvmPvUnhalt                     = QemuCPUFeature("kvm-pv-unhalt")
	QemuCPUFeatureKvmStealTime                    = QemuCPUFeature("kvm-steal-time")
	QemuCPUFeatureLa57                            = QemuCPUFeature("la57")
	QemuCPUFeatureLahfLm                          = QemuCPUFeature("lahf-lm")
	QemuCPUFeatureLbrv                            = QemuCPUFeature("lbrv")
	QemuCPUFeatureLm                              = QemuCPUFeature("lm")
	QemuCPUFeatureLwp                             = QemuCPUFeature("lwp")
	QemuCPUFeatureMca                             = QemuCPUFeature("mca")
	QemuCPUFeatureMce                             = QemuCPUFeature("mce")
	QemuCPUFeatureMdClear                         = QemuCPUFeature("md-clear")
	QemuCPUFeatureMdsNo                           = QemuCPUFeature("mds-no")
	QemuCPUFeatureMisalignsse                     = QemuCPUFeature("misalignsse")
	QemuCPUFeatureMmx                             = QemuCPUFeature("mmx")
	QemuCPUFeatureMmxext                          = QemuCPUFeature("mmxext")
	QemuCPUFeatureMonitor                         = QemuCPUFeature("monitor")
	QemuCPUFeatureMovbe                           = QemuCPUFeature("movbe")
	QemuCPUFeatureMovdir64b                       = QemuCPUFeature("movdir64b")
	QemuCPUFeatureMovdiri                         = QemuCPUFeature("movdiri")
	QemuCPUFeatureMpx                             = QemuCPUFeature("mpx")
	QemuCPUFeatureMsr                             = QemuCPUFeature("msr")
	QemuCPUFeatureMtrr                            = QemuCPUFeature("mtrr")
	QemuCPUFeatureNodeidMsr                       = QemuCPUFeature("nodeid-msr")
	QemuCPUFeatureNpt                             = QemuCPUFeature("npt")
	QemuCPUFeatureNripSave                        = QemuCPUFeature("nrip-save")
	QemuCPUFeatureNx                              = QemuCPUFeature("nx")
	QemuCPUFeatureOsvw                            = QemuCPUFeature("osvw")
	QemuCPUFeaturePae                             = QemuCPUFeature("pae")
	QemuCPUFeaturePat                             = QemuCPUFeature("pat")
	QemuCPUFeaturePauseFilter                     = QemuCPUFeature("pause-filter")
	QemuCPUFeaturePbe                             = QemuCPUFeature("pbe")
	QemuCPUFeaturePcid                            = QemuCPUFeature("pcid")
	QemuCPUFeaturePclmulqdq                       = QemuCPUFeature("pclmulqdq")
	QemuCPUFeaturePcommit                         = QemuCPUFeature("pcommit")
	QemuCPUFeaturePdcm                            = QemuCPUFeature("pdcm")
	QemuCPUFeaturePdpe1gb                         = QemuCPUFeature("pdpe1gb")
	QemuCPUFeaturePerfctrCore                     = QemuCPUFeature("perfctr-core")
	QemuCPUFeaturePerfctrNb                       = QemuCPUFeature("perfctr-nb")
	QemuCPUFeaturePfthreshold                     = QemuCPUFeature("pfthreshold")
	QemuCPUFeaturePge                             = QemuCPUFeature("pge")
	QemuCPUFeaturePhe                             = QemuCPUFeature("phe")
	QemuCPUFeaturePheEn                           = QemuCPUFeature("phe-en")
	QemuCPUFeaturePku                             = QemuCPUFeature("pku")
	QemuCPUFeaturePmm                             = QemuCPUFeature("pmm")
	QemuCPUFeaturePmmEn                           = QemuCPUFeature("pmm-en")
	QemuCPUFeaturePmu                             = QemuCPUFeature("pmu")
	QemuCPUFeaturePn                              = QemuCPUFeature("pn")
	QemuCPUFeaturePni                             = QemuCPUFeature("pni")
	QemuCPUFeaturePopcnt                          = QemuCPUFeature("popcnt")
	QemuCPUFeaturePschangeMcNo                    = QemuCPUFeature("pschange-mc-no")
	QemuCPUFeaturePse                             = QemuCPUFeature("pse")
	QemuCPUFeaturePse36                           = QemuCPUFeature("pse36")
	QemuCPUFeatureRdctlNo                         = QemuCPUFeature("rdctl-no")
	QemuCPUFeatureRdpid                           = QemuCPUFeature("rdpid")
	QemuCPUFeatureRdrand                          = QemuCPUFeature("rdrand")
	QemuCPUFeatureRdseed                          = QemuCPUFeature("rdseed")
	QemuCPUFeatureRdtscp                          = QemuCPUFeature("rdtscp")
	QemuCPUFeatureRsba                            = QemuCPUFeature("rsba")
	QemuCPUFeatureRtm                             = QemuCPUFeature("rtm")
	QemuCPUFeatureSep                             = QemuCPUFeature("sep")
	QemuCPUFeatureSerialize                       = QemuCPUFeature("serialize")
	QemuCPUFeatureShaNi                           = QemuCPUFeature("sha-ni")
	QemuCPUFeatureSkinit                          = QemuCPUFeature("skinit")
	QemuCPUFeatureSkipL1dflVmentry                = QemuCPUFeature("skip-l1dfl-vmentry")
	QemuCPUFeatureSmap                            = QemuCPUFeature("smap")
	QemuCPUFeatureSmep                            = QemuCPUFeature("smep")
	QemuCPUFeatureSmx                             = QemuCPUFeature("smx")
	QemuCPUFeatureSpecCtrl                        = QemuCPUFeature("spec-ctrl")
	QemuCPUFeatureSplitLockDetect                 = QemuCPUFeature("split-lock-detect")
	QemuCPUFeatureSs                              = QemuCPUFeature("ss")
	QemuCPUFeatureSsbd                            = QemuCPUFeature("ssbd")
	QemuCPUFeatureSsbNo                           = QemuCPUFeature("ssb-no")
	QemuCPUFeatureSse                             = QemuCPUFeature("sse")
	QemuCPUFeatureSse2                            = QemuCPUFeature("sse2")
	QemuCPUFeatureSse4_1                          = QemuCPUFeature("sse4.1")
	QemuCPUFeatureSse4_2                          = QemuCPUFeature("sse4.2")
	QemuCPUFeatureSse4a                           = QemuCPUFeature("sse4a")
	QemuCPUFeatureSsse3                           = QemuCPUFeature("ssse3")
	QemuCPUFeatureStibp                           = QemuCPUFeature("stibp")
	QemuCPUFeatureSvm                             = QemuCPUFeature("svm")
	QemuCPUFeatureSvmLock                         = QemuCPUFeature("svm-lock")
	QemuCPUFeatureSyscall                         = QemuCPUFeature("syscall")
	QemuCPUFeatureTaaNo                           = QemuCPUFeature("taa-no")
	QemuCPUFeatureTbm                             = QemuCPUFeature("tbm")
	QemuCPUFeatureTce                             = QemuCPUFeature("tce")
	QemuCPUFeatureTm                              = QemuCPUFeature("tm")
	QemuCPUFeatureTm2                             = QemuCPUFeature("tm2")
	QemuCPUFeatureTopoext                         = QemuCPUFeature("topoext")
	QemuCPUFeatureTsc                             = QemuCPUFeature("tsc")
	QemuCPUFeatureTscAdjust                       = QemuCPUFeature("tsc-adjust")
	QemuCPUFeatureTscDeadline                     = QemuCPUFeature("tsc-deadline")
	QemuCPUFeatureTscScale                        = QemuCPUFeature("tsc-scale")
	QemuCPUFeatureTsxCtrl                         = QemuCPUFeature("tsx-ctrl")
	QemuCPUFeatureTsxLdtrk                        = QemuCPUFeature("tsx-ldtrk")
	QemuCPUFeatureUmip                            = QemuCPUFeature("umip")
	QemuCPUFeatureVaes                            = QemuCPUFeature("vaes")
	QemuCPUFeatureVirtSsbd                        = QemuCPUFeature("virt-ssbd")
	QemuCPUFeatureVmcbClean                       = QemuCPUFeature("vmcb-clean")
	QemuCPUFeatureVme                             = QemuCPUFeature("vme")
	QemuCPUFeatureVmx                             = QemuCPUFeature("vmx")
	QemuCPUFeatureVmxActivityHlt                  = QemuCPUFeature("vmx-activity-hlt")
	QemuCPUFeatureVmxActivityShutdown             = QemuCPUFeature("vmx-activity-shutdown")
	QemuCPUFeatureVmxActivityWaitSipi             = QemuCPUFeature("vmx-activity-wait-sipi")
	QemuCPUFeatureVmxApicvRegister                = QemuCPUFeature("vmx-apicv-register")
	QemuCPUFeatureVmxApicvVid                     = QemuCPUFeature("vmx-apicv-vid")
	QemuCPUFeatureVmxApicvX2apic                  = QemuCPUFeature("vmx-apicv-x2apic")
	QemuCPUFeatureVmxApicvXapic                   = QemuCPUFeature("vmx-apicv-xapic")
	QemuCPUFeatureVmxCr3LoadNoexit                = QemuCPUFeature("vmx-cr3-load-noexit")
	QemuCPUFeatureVmxCr3StoreNoexit               = QemuCPUFeature("vmx-cr3-store-noexit")
	QemuCPUFeatureVmxCr8LoadExit                  = QemuCPUFeature("vmx-cr8-load-exit")
	QemuCPUFeatureVmxCr8StoreExit                 = QemuCPUFeature("vmx-cr8-store-exit")
	QemuCPUFeatureVmxDescExit                     = QemuCPUFeature("vmx-desc-exit")
	QemuCPUFeatureVmxEnclsExit                    = QemuCPUFeature("vmx-encls-exit")
	QemuCPUFeatureVmxEntryIa32eMode               = QemuCPUFeature("vmx-entry-ia32e-mode")
	QemuCPUFeatureVmxEntryLoadBndcfgs             = QemuCPUFeature("vmx-entry-load-bndcfgs")
	QemuCPUFeatureVmxEntryLoadEfer                = QemuCPUFeature("vmx-entry-load-efer")
	QemuCPUFeatureVmxEntryLoadPat                 = QemuCPUFeature("vmx-entry-load-pat")
	QemuCPUFeatureVmxEntryLoadPerfGlobalCtrl      = QemuCPUFeature("vmx-entry-load-perf-global-ctrl")
	QemuCPUFeatureVmxEntryLoadRtitCtl             = QemuCPUFeature("vmx-entry-load-rtit-ctl")
	QemuCPUFeatureVmxEntryNoloadDebugctl          = QemuCPUFeature("vmx-entry-noload-debugctl")
	QemuCPUFeatureVmxEpt                          = QemuCPUFeature("vmx-ept")
	QemuCPUFeatureVmxEpt1gb                       = QemuCPUFeature("vmx-ept-1gb")
	QemuCPUFeatureVmxEpt2mb                       = QemuCPUFeature("vmx-ept-2mb")
	QemuCPUFeatureVmxEptad                        = QemuCPUFeature("vmx-eptad")
	QemuCPUFeatureVmxEptAdvancedExitinfo          = QemuCPUFeature("vmx-ept-advanced-exitinfo")
	QemuCPUFeatureVmxEptExeconly                  = QemuCPUFeature("vmx-ept-execonly")
	QemuCPUFeatureVmxEptpSwitching                = QemuCPUFeature("vmx-eptp-switching")
	QemuCPUFeatureVmxExitAckIntr                  = QemuCPUFeature("vmx-exit-ack-intr")
	QemuCPUFeatureVmxExitClearBndcfgs             = QemuCPUFeature("vmx-exit-clear-bndcfgs")
	QemuCPUFeatureVmxExitClearRtitCtl             = QemuCPUFeature("vmx-exit-clear-rtit-ctl")
	QemuCPUFeatureVmxExitLoadEfer                 = QemuCPUFeature("vmx-exit-load-efer")
	QemuCPUFeatureVmxExitLoadPat                  = QemuCPUFeature("vmx-exit-load-pat")
	QemuCPUFeatureVmxExitLoadPerfGlobalCtrl       = QemuCPUFeature("vmx-exit-load-perf-global-ctrl")
	QemuCPUFeatureVmxExitNosaveDebugctl           = QemuCPUFeature("vmx-exit-nosave-debugctl")
	QemuCPUFeatureVmxExitSaveEfer                 = QemuCPUFeature("vmx-exit-save-efer")
	QemuCPUFeatureVmxExitSavePat                  = QemuCPUFeature("vmx-exit-save-pat")
	QemuCPUFeatureVmxExitSavePreemptionTimer      = QemuCPUFeature("vmx-exit-save-preemption-timer")
	QemuCPUFeatureVmxFlexpriority                 = QemuCPUFeature("vmx-flexpriority")
	QemuCPUFeatureVmxHltExit                      = QemuCPUFeature("vmx-hlt-exit")
	QemuCPUFeatureVmxInsOuts                      = QemuCPUFeature("vmx-ins-outs")
	QemuCPUFeatureVmxIntrExit                     = QemuCPUFeature("vmx-intr-exit")
	QemuCPUFeatureVmxInvept                       = QemuCPUFeature("vmx-invept")
	QemuCPUFeatureVmxInveptAllContext             = QemuCPUFeature("vmx-invept-all-context")
	QemuCPUFeatureVmxInveptSingleContext          = QemuCPUFeature("vmx-invept-single-context")
	QemuCPUFeatureVmxInveptSingleContextNoglobals = QemuCPUFeature("vmx-invept-single-context-noglobals")
	QemuCPUFeatureVmxInvlpgExit                   = QemuCPUFeature("vmx-invlpg-exit")
	QemuCPUFeatureVmxInvpcidExit                  = QemuCPUFeature("vmx-invpcid-exit")
	QemuCPUFeatureVmxInvvpid                      = QemuCPUFeature("vmx-invvpid")
	QemuCPUFeatureVmxInvvpidAllContext            = QemuCPUFeature("vmx-invvpid-all-context")
	QemuCPUFeatureVmxInvvpidSingleAddr            = QemuCPUFeature("vmx-invvpid-single-addr")
	QemuCPUFeatureVmxIoBitmap                     = QemuCPUFeature("vmx-io-bitmap")
	QemuCPUFeatureVmxIoExit                       = QemuCPUFeature("vmx-io-exit")
	QemuCPUFeatureVmxMonitorExit                  = QemuCPUFeature("vmx-monitor-exit")
	QemuCPUFeatureVmxMovdrExit                    = QemuCPUFeature("vmx-movdr-exit")
	QemuCPUFeatureVmxMsrBitmap                    = QemuCPUFeature("vmx-msr-bitmap")
	QemuCPUFeatureVmxMtf                          = QemuCPUFeature("vmx-mtf")
	QemuCPUFeatureVmxMwaitExit                    = QemuCPUFeature("vmx-mwait-exit")
	QemuCPUFeatureVmxNmiExit                      = QemuCPUFeature("vmx-nmi-exit")
	QemuCPUFeatureVmxPageWalk4                    = QemuCPUFeature("vmx-page-walk-4")
	QemuCPUFeatureVmxPageWalk5                    = QemuCPUFeature("vmx-page-walk-5")
	QemuCPUFeatureVmxPauseExit                    = QemuCPUFeature("vmx-pause-exit")
	QemuCPUFeatureVmxPle                          = QemuCPUFeature("vmx-ple")
	QemuCPUFeatureVmxPml                          = QemuCPUFeature("vmx-pml")
	QemuCPUFeatureVmxPostedIntr                   = QemuCPUFeature("vmx-posted-intr")
	QemuCPUFeatureVmxPreemptionTimer              = QemuCPUFeature("vmx-preemption-timer")
	QemuCPUFeatureVmxRdpmcExit                    = QemuCPUFeature("vmx-rdpmc-exit")
	QemuCPUFeatureVmxRdrandExit                   = QemuCPUFeature("vmx-rdrand-exit")
	QemuCPUFeatureVmxRdseedExit                   = QemuCPUFeature("vmx-rdseed-exit")
	QemuCPUFeatureVmxRdtscExit                    = QemuCPUFeature("vmx-rdtsc-exit")
	QemuCPUFeatureVmxRdtscpExit                   = QemuCPUFeature("vmx-rdtscp-exit")
	QemuCPUFeatureVmxSecondaryCtls                = QemuCPUFeature("vmx-secondary-ctls")
	QemuCPUFeatureVmxShadowVmcs                   = QemuCPUFeature("vmx-shadow-vmcs")
	QemuCPUFeatureVmxStoreLma                     = QemuCPUFeature("vmx-store-lma")
	QemuCPUFeatureVmxTrueCtls                     = QemuCPUFeature("vmx-true-ctls")
	QemuCPUFeatureVmxTscOffset                    = QemuCPUFeature("vmx-tsc-offset")
	QemuCPUFeatureVmxUnrestrictedGuest            = QemuCPUFeature("vmx-unrestricted-guest")
	QemuCPUFeatureVmxVintrPending                 = QemuCPUFeature("vmx-vintr-pending")
	QemuCPUFeatureVmxVmfunc                       = QemuCPUFeature("vmx-vmfunc")
	QemuCPUFeatureVmxVmwriteVmexitFields          = QemuCPUFeature("vmx-vmwrite-vmexit-fields")
	QemuCPUFeatureVmxVnmi                         = QemuCPUFeature("vmx-vnmi")
	QemuCPUFeatureVmxVnmiPending                  = QemuCPUFeature("vmx-vnmi-pending")
	QemuCPUFeatureVmxVpid                         = QemuCPUFeature("vmx-vpid")
	QemuCPUFeatureVmxWbinvdExit                   = QemuCPUFeature("vmx-wbinvd-exit")
	QemuCPUFeatureVmxXsaves                       = QemuCPUFeature("vmx-xsaves")
	QemuCPUFeatureVmxZeroLenInject                = QemuCPUFeature("vmx-zero-len-inject")
	QemuCPUFeatureVpclmulqdq                      = QemuCPUFeature("vpclmulqdq")
	QemuCPUFeatureWaitpkg                         = QemuCPUFeature("waitpkg")
	QemuCPUFeatureWbnoinvd                        = QemuCPUFeature("wbnoinvd")
	QemuCPUFeatureWdt                             = QemuCPUFeature("wdt")
	QemuCPUFeatureX2apic                          = QemuCPUFeature("x2apic")
	QemuCPUFeatureXcrypt                          = QemuCPUFeature("xcrypt")
	QemuCPUFeatureXcryptEn                        = QemuCPUFeature("xcrypt-en")
	QemuCPUFeatureXgetbv1                         = QemuCPUFeature("xgetbv1")
	QemuCPUFeatureXop                             = QemuCPUFeature("xop")
	QemuCPUFeatureXsave                           = QemuCPUFeature("xsave")
	QemuCPUFeatureXsavec                          = QemuCPUFeature("xsavec")
	QemuCPUFeatureXsaveerptr                      = QemuCPUFeature("xsaveerptr")
	QemuCPUFeatureXsaveopt                        = QemuCPUFeature("xsaveopt")
	QemuCPUFeatureXsaves                          = QemuCPUFeature("xsaves")
	QemuCPUFeatureXstore                          = QemuCPUFeature("xstore")
	QemuCPUFeatureXstoreEn                        = QemuCPUFeature("xstore-en")
	QemuCPUFeatureXtpr                            = QemuCPUFeature("xtpr")
)
