name: buildenvs/myself

on:
  push:
    branches:
      - stable
    paths:
      - 'buildenvs/myself.Dockerfile'
      - '.github/workflows/myself.yaml'

jobs:
  myself-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./buildenvs/myself.Dockerfile
          platforms: linux/amd64
          tags: index.unikraft.io/kraftkit.sh/myself:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
