name: prerelease

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container: kraftkit.sh/myself-full:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Fetch all tags
        run: |
          git config --global --add safe.directory /__w/kraftkit/kraftkit
          git fetch --force --tags

      - name: Generate GoReleaser configuration
        run: |
          ytt -f .goreleaser-prerelease.yaml > goreleaser-prerelease.yaml

      - name: Run GoReleaser
        run: |
          git tag -d "$(git describe)" || true
          git config user.name "Unikraft Bot"
          git config user.email "monkey@unikraft.io"
          git tag -a "$(git describe)" -m "Pre-release: $(git describe)"
          echo "$GOOGLE_APPLICATION_JSON" > /tmp/gs.json
          goreleaser build \
            --config goreleaser-prerelease.yaml \
            --skip-validate
          goreleaser release \
            --config goreleaser-prerelease.yaml \
            --rm-dist \
            --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
